### ISSUE TITLE
Exception that "ExtensionDirector is destroyed" when reinstall biz module with dubbo 3.2 and nacos 

### ISSUE THREAD

**Issue by rapidark** [koupleless/koupleless#153]
### Describe the question or bug

uninstall biz module and then reinstall biz module, exception happened:
ExtensionDirector is destroyed at org.apache.dubbo.common.extension.ExtensionDirector.checkDestroyed(ExtensionDirector.java:157) ~[dubbo-3.2.7.jar:3.2.7]

### Expected behavior

reinstall biz module success

### Actual behavior

`
Caused by: java.lang.IllegalStateException: ExtensionDirector is destroyed
	at org.apache.dubbo.common.extension.ExtensionDirector.checkDestroyed(ExtensionDirector.java:157) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.common.extension.ExtensionDirector.getExtensionLoader(ExtensionDirector.java:68) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.common.threadpool.manager.DefaultExecutorRepository.createExecutor(DefaultExecutorRepository.java:187) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.common.threadpool.manager.IsolationExecutorRepository.createExecutor(IsolationExecutorRepository.java:71) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.common.threadpool.manager.DefaultExecutorRepository.lambda$createExecutorIfAbsent$1(DefaultExecutorRepository.java:107) ~[dubbo-3.2.7.jar:3.2.7]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at org.apache.dubbo.common.utils.ConcurrentHashMapUtils.computeIfAbsent(ConcurrentHashMapUtils.java:58) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.common.threadpool.manager.DefaultExecutorRepository.createExecutorIfAbsent(DefaultExecutorRepository.java:107) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.remoting.transport.AbstractServer.reset(AbstractServer.java:103) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeServer.reset(HeaderExchangeServer.java:211) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocolServer.reset(DubboProtocolServer.java:59) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.openServer(DubboProtocol.java:358) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.export(DubboProtocol.java:332) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:73) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.export(ProtocolSecurityWrapper.java:83) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:79) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:61) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.export(InvokerCountWrapper.java:42) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.integration.RegistryProtocol.lambda$doLocalExport$5(RegistryProtocol.java:333) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.integration.ExporterFactory.lambda$createExporter$0(ExporterFactory.java:32) ~[dubbo-3.2.7.jar:3.2.7]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at org.apache.dubbo.registry.integration.ExporterFactory.createExporter(ExporterFactory.java:29) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.integration.RegistryProtocol.doLocalExport(RegistryProtocol.java:333) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:273) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:66) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.export(ProtocolSecurityWrapper.java:83) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:79) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.export(InvokerCountWrapper.java:42) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:861) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.ServiceConfig.exportRemote(ServiceConfig.java:830) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:771) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:554) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:536) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:498) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:327) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:438) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:393) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:167) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:148) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:155) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:141) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:52) ~[dubbo-3.2.7.jar:3.2.7]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:149) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:451) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:384) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:981) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:627) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.2.jar:3.2.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.2.jar:3.2.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.2.jar:3.2.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.2.jar:3.2.2]
	at com.rapidark.resource.RapidarkResourceApplication.main(RapidarkResourceApplication.java:27) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48) ~[sofa-ark-archive-3.1.0.jar:?]
	at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:289) ~[sofa-ark-container-3.1.0.jar:?]
	at com.alipay.sofa.ark.api.ArkClient.installBiz(ArkClient.java:168) ~[sofa-ark-api-3.1.0.jar:?]
	at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:349) ~[sofa-ark-api-3.1.0.jar:?]
	at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:328) ~[sofa-ark-api-3.1.0.jar:?]
	at com.alipay.sofa.koupleless.arklet.core.ops.UnifiedOperationServiceImpl.install(UnifiedOperationServiceImpl.java:67) ~[arklet-core-2.1.0.jar:?]
	at com.alipay.sofa.koupleless.arklet.core.command.builtin.handler.InstallBizHandler.handle(InstallBizHandler.java:64) ~[arklet-core-2.1.0.jar:?]
	... 35 more
`

### Steps to reproduce

Example:  https://github.com/rapidark/koupleless-dubbo3nacos-example

1. run base project: rapidark-os-runner
2. install biz module: rapidark-os-apps/rapidark-resource
3. uninstall biz module
4. reinstall biz module, see the error

### Environment

- Koupleless version: 2.1.0
- SOFAArk version: 3.1.0
- JVM version: Oracle Jdk 17

**Comment by gaosaroma** [comment]
same as https://github.com/koupleless/koupleless/issues/203

**Comment by lvjing2** [comment]
will fix in #203
