### ISSUE TITLE
跨模块调用 BaseRuntimeAutoConfiguration 初始化异常

### ISSUE THREAD

**Issue by 98DE9E1F** [koupleless/koupleless#181]
### Describe the question or bug

当业务应用不存在跨模块调用时，自动初始化了BaseRuntimeAutoConfiguration.ArkAutowiredBeanPostProcessor，导致一下报错

`
Caused by: org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanTypeDeductionException: Failed to deduce bean type for com.alipay.sofa.koupleless.plugin.BaseRuntimeAutoConfiguration.arkAutowiredBeanPostProcessor
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$Spec.deducedBeanTypeForBeanMethod(OnBeanCondition.java:519)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$Spec.deducedBeanType(OnBeanCondition.java:508)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$Spec.<init>(OnBeanCondition.java:431)
	... 35 more
Caused by: com.alipay.sofa.ark.exception.ArkLoaderException: [ArkBiz Loader] jupiter-web:1.0.0 : can not load class: com.alipay.sofa.koupleless.common.service.ArkAutowiredBeanPostProcessor`

### Environment

- Koupleless version (see CURRENT_VERSION.txt): 2.0.0
- SOFAArk version: 3.0.4-SNAPSHOT
- JVM version (e.g. `java -version`): JDK17

**Comment by lvjing2** [comment]
看上去是模块必须引入 koupleless-app-starter，不然就会报这个错误。希望是模块不需要用到跨模块调用时，可以不引入 koupleless-app- starter 这个依赖
