### ISSUE TITLE
Dubbo 3.2.x 适配

### ISSUE THREAD

**Issue by gaosaroma** [koupleless/koupleless#203]
### Describe the question or bug

在 Dubbo3.2.x 中，模块在经历：安装 -> 卸载 -> 再次安装时报错。

比如如果模块使用 DubboProtocol，DubboProtocol 中的 `serverMap` 字段以 `host:port` 为 key，以 `ProtocolServer` 为 value。在模块卸载时，会将相应的 ProtocolServer 关闭，在模块再次安装时，会使用到已经关闭的 ProtocolServer 从而报错。

- 代码

org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol#openServer

![image](https://github.com/koupleless/koupleless/assets/44571204/d8f4197f-9a50-4d31-be3e-b373b2e3ae5e)

- 报错

> Caused by: java.lang.IllegalStateException: ExtensionDirector is destroyed at org.apache.dubbo.common.extension.ExtensionDirector.checkDestroyed(ExtensionDirector.java:157) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.common.extension.ExtensionDirector.getExtensionLoader(ExtensionDirector.java:68) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.common.threadpool.manager.DefaultExecutorRepository.createExecutor(DefaultExecutorRepository.java:187) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.common.threadpool.manager.IsolationExecutorRepository.createExecutor(IsolationExecutorRepository.java:71) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.common.threadpool.manager.DefaultExecutorRepository.lambda$createExecutorIfAbsent$1(DefaultExecutorRepository.java:107) ~[dubbo-3.2.7.jar:3.2.7] at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?] at org.apache.dubbo.common.utils.ConcurrentHashMapUtils.computeIfAbsent(ConcurrentHashMapUtils.java:58) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.common.threadpool.manager.DefaultExecutorRepository.createExecutorIfAbsent(DefaultExecutorRepository.java:107) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.remoting.transport.AbstractServer.reset(AbstractServer.java:103) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeServer.reset(HeaderExchangeServer.java:211) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocolServer.reset(DubboProtocolServer.java:59) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.openServer(DubboProtocol.java:358) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.export(DubboProtocol.java:332) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:73) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.export(ProtocolSecurityWrapper.java:83) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:79) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:61) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.export(InvokerCountWrapper.java:42) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.registry.integration.RegistryProtocol.lambda$doLocalExport$5(RegistryProtocol.java:333) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.registry.integration.ExporterFactory.lambda$createExporter$0(ExporterFactory.java:32) ~[dubbo-3.2.7.jar:3.2.7] at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?] at org.apache.dubbo.registry.integration.ExporterFactory.createExporter(ExporterFactory.java:29) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.registry.integration.RegistryProtocol.doLocalExport(RegistryProtocol.java:333) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:273) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:66) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.export(ProtocolSecurityWrapper.java:83) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:79) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.export(InvokerCountWrapper.java:42) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:861) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.config.ServiceConfig.exportRemote(ServiceConfig.java:830) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:771) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:554) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:536) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:498) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:327) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:438) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:393) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:167) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:148) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:155) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:141) ~[dubbo-3.2.7.jar:3.2.7] at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:52) ~[dubbo-3.2.7.jar:3.2.7] at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178) ~[spring-context-6.1.3.jar:6.1.3] at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171) ~[spring-context-6.1.3.jar:6.1.3] at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:149) ~[spring-context-6.1.3.jar:6.1.3] at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:451) ~[spring-context-6.1.3.jar:6.1.3] at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:384) ~[spring-context-6.1.3.jar:6.1.3] at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:981) ~[spring-context-6.1.3.jar:6.1.3] at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:627) ~[spring-context-6.1.3.jar:6.1.3] at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.2.jar:3.2.2] at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.2.jar:3.2.2] at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.2.jar:3.2.2] at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.2.jar:3.2.2] at com.rapidark.resource.RapidarkResourceApplication.main(RapidarkResourceApplication.java:27) ~[?:?] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48) ~[sofa-ark-archive-3.1.0.jar:?] at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:289) ~[sofa-ark-container-3.1.0.jar:?] at com.alipay.sofa.ark.api.ArkClient.installBiz(ArkClient.java:168) ~[sofa-ark-api-3.1.0.jar:?] at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:349) ~[sofa-ark-api-3.1.0.jar:?] at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:328) ~[sofa-ark-api-3.1.0.jar:?] at com.alipay.sofa.koupleless.arklet.core.ops.UnifiedOperationServiceImpl.install(UnifiedOperationServiceImpl.java:67) ~[arklet-core-2.1.0.jar:?] at com.alipay.sofa.koupleless.arklet.core.command.builtin.handler.InstallBizHandler.handle(InstallBizHandler.java:64) ~[arklet-core-2.1.0.jar:?] ... 35 more

再比如说在模块卸载时，项目中的 FrameworkExecutorRepository#cacheRefreshingScheduledExecutor 会被关闭。

- 在模块再次安装时，可以看到项目的 executor 被关闭了：

![image](https://github.com/koupleless/koupleless/assets/44571204/28a8b719-ad9f-4133-b707-ec30436af180)

- 报错如：

> java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@259264a6[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@34d4f75d[Wrapped task = org.apache.dubbo.metadata.AbstractCacheManager$CacheRefreshTask@1dcca896]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@72bd9b9d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:680)
	at java.base/java.util.concurrent.Executors$DelegatedScheduledExecutorService.scheduleWithFixedDelay(Executors.java:822)
	at org.apache.dubbo.metadata.AbstractCacheManager.init(AbstractCacheManager.java:67)
	at org.apache.dubbo.registry.client.metadata.store.MetaCacheManager.<init>(MetaCacheManager.java:56)
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.<init>(AbstractServiceDiscovery.java:102)
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.<init>(AbstractServiceDiscovery.java:84)
	at org.apache.dubbo.registry.nacos.NacosServiceDiscovery.<init>(NacosServiceDiscovery.java:78)
	at org.apache.dubbo.registry.nacos.NacosServiceDiscoveryFactory.createDiscovery(NacosServiceDiscoveryFactory.java:41)
	at org.apache.dubbo.registry.client.AbstractServiceDiscoveryFactory.lambda$getServiceDiscovery$0(AbstractServiceDiscoveryFactory.java:54)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.apache.dubbo.common.utils.ConcurrentHashMapUtils.computeIfAbsent(ConcurrentHashMapUtils.java:58)
	at org.apache.dubbo.registry.client.AbstractServiceDiscoveryFactory.getServiceDiscovery(AbstractServiceDiscoveryFactory.java:54)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.getServiceDiscovery(ServiceDiscoveryRegistry.java:127)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.createServiceDiscovery(ServiceDiscoveryRegistry.java:114)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.<init>(ServiceDiscoveryRegistry.java:91)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryFactory.createRegistry(ServiceDiscoveryRegistryFactory.java:40)
	at org.apache.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:95)
	at org.apache.dubbo.registry.RegistryFactoryWrapper.getRegistry(RegistryFactoryWrapper.java:33)
	at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
	at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:446)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:276)
	at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.export(ProtocolSecurityWrapper.java:83)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:79)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:66)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58)
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47)
	at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.export(InvokerCountWrapper.java:42)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:861)
	at org.apache.dubbo.config.ServiceConfig.exportRemote(ServiceConfig.java:830)
	at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:771)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:554)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:536)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:498)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:327)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:438)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:393)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:167)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:148)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:155)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:141)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:52)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:149)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:451)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:384)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:981)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:627)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
	at com.rapidark.resource.RapidarkResourceApplication.main(RapidarkResourceApplication.java:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:289)
	at com.alipay.sofa.ark.api.ArkClient.installBiz(ArkClient.java:168)
	at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:343)
	at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:328)

### Environment

- Koupleless version : 2.1.0
- SOFAArk version: 3.1.0
- JVM version (e.g. `java -version`): 17
- OS version (e.g. `uname -a`): Mac
- dubbo-spring-boot-actuator version: 3.2.7
- spring-boot version: 3.2.2
- spring-cloud.version: 2023.0.0

**Comment by gaosaroma** [comment]
same as https://github.com/koupleless/koupleless/issues/153

**Comment by CodeNoobKing** [comment]
基座需要启动 dubbo，在基座的 Springboot 启动类中加载 EnableDubbo 即可。
否则会造成 dubbo 一些全局缓存的，公共的 ExtensionLoader，在模块 ScopeModel 被关闭的时候随之关闭。
