### ISSUE TITLE
静态合并部署时，如果插件目录下存在多个插件，JMX报错

### ISSUE THREAD

**Issue by huyuans** [koupleless/koupleless#232]
_sofa相关版本：
<koupleless.runtime.version>2.0.0</koupleless.runtime.version>
<sofa.ark.version>3.0.3</sofa.ark.version>
<sofa.common.tools.version>2.0.3</sofa.common.tools.version>
springboot版本：
 <spring-boot.version>3.1.5</spring-boot.version>_

**当vm参数com.alipay.sofa.ark.static.biz.dir所指定的目录下放置多个biz插件时，当基座启动后加载每个biz模块的TomcatWebServerFactoryCustomizer时会报JMX错误，堆栈信息如下**：

javax.management.InstanceAlreadyExistsException: Tomcat:type=Valve,host=localhost,seq=1,name=ErrorReportValve
	at java.management/com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:436)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1865)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:960)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:895)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:523)
	at org.apache.tomcat.util.modeler.Registry.registerComponent(Registry.java:632)
	at org.apache.catalina.util.LifecycleMBeanBase.register(LifecycleMBeanBase.java:152)
	at org.apache.catalina.util.LifecycleMBeanBase.initInternal(LifecycleMBeanBase.java:53)
	at org.apache.catalina.valves.ValveBase.initInternal(ValveBase.java:132)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:127)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:161)
	at org.apache.catalina.core.StandardPipeline.addValve(StandardPipeline.java:332)
	at org.springframework.boot.autoconfigure.web.embedded.TomcatWebServerFactoryCustomizer.lambda$customizeErrorReportValve$25(TomcatWebServerFactoryCustomizer.java:339)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.configureContext(TomcatServletWebServerFactory.java:403)
	at com.alipay.sofa.ark.springboot.web.ArkTomcatServletWebServerFactory.prepareContext(ArkTomcatServletWebServerFactory.java:203)
	at com.alipay.sofa.ark.springboot.web.ArkTomcatServletWebServerFactory.getWebServer(ArkTomcatServletWebServerFactory.java:93)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:183)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:161)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:610)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)

**Comment by lvjing2** [comment]
只会报错，不影响模块启动成功
