### ISSUE TITLE
 无法在自定义`-cp`配置下加载`BizRuntimeContext`

### ISSUE THREAD

**Issue by qianbidaos** [koupleless/koupleless#333]
**描述**:
在使用以下命令启动应用时，应用启动失败，无法加载`BizRuntimeContext`，报错信息如下：

```bash
java -cp "/Users/qianbidao/IdeaProjects/DJI-Cloud/zzy/lib/BOOT-INF/lib/*:/Users/qianbidao/IdeaProjects/DJI-Cloud/djicloud/target/classes:/Users/qianbidao/IdeaProjects/DJI-Cloud/zzy/lib/org" -Dloader.main=com.dji.sample.DjiApplication org.springframework.boot.loader.JarLauncher
```

**错误日志**:
```
2024-11-06 14:47:52 [main] ERROR o.s.boot.SpringApplication - Application run failed
com.alipay.sofa.koupleless.common.exception.BizRuntimeException: No BizRuntimeContext found for classLoader: org.springframework.boot.loader.LaunchedURLClassLoader@687080dc
    at com.alipay.sofa.koupleless.common.BizRuntimeContextRegistry.getBizRuntimeContextByClassLoader(BizRuntimeContextRegistry.java:116)
    at com.alipay.sofa.koupleless.plugin.spring.BizApplicationContextInitializer.initialize(BizApplicationContextInitializer.java:32)
    ...
```

**环境**:
- JDK版本: 17
- Spring Boot版本: 2.7.2
- 使用了`org.springframework.boot.loader.JarLauncher`作为主类
- MANIFEST.MF配置:
  ```
  Manifest-Version: 1.0
  Created-By: Maven JAR Plugin 3.2.2
  Build-Jdk-Spec: 17
  Implementation-Title: djicloud
  Implementation-Version: 1.9.0
  Main-Class: org.springframework.boot.loader.JarLauncher
  Start-Class: com.dji.sample.DjiApplication
  Spring-Boot-Version: 2.7.2
  Spring-Boot-Classes: BOOT-INF/classes/
  Spring-Boot-Lib: BOOT-INF/lib/
  ```

**问题**:
使用上述`-cp`命令配置启动时，应用无法加载biz环境。初步怀疑是`classloader`或SOFA框架初始化的问题。

**期望行为**:
应用可以正常启动，并成功加载`BizRuntimeContext`。

我已经确保依赖的库路径在`-cp`中正确加载。

**可能的解决方案**:
1. 是否需要调整`classloader`的配置。
2. SOFA框架是否有特殊的classloader要求。

**Comment by qianbidaos** [comment]
此场景cp命令无法使用org.springframework.boot.loader.JarLauncher 替换成 org.springframework.boot.loader.PropertiesLauncher 报以上错误,jarlaunch报错

Exception in thread "main" java.lang.IllegalStateException: No 'Start-Class' manifest entry specified in org.springframework.boot.loader.JarLauncher@27808f31
        at org.springframework.boot.loader.ExecutableArchiveLauncher.getMainClass(ExecutableArchiveLauncher.java:95)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:57)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)


这个问题先不要清理我留个档
