### ISSUE TITLE
Unable to instantiate com.alipay.sofa.koupleless.adapter.ApolloPropertiesClearInitializer [org.springframework.boot.env.EnvironmentPostProcessor]

### ISSUE THREAD

**Issue by Marco-Zheng** [koupleless/koupleless#367]
### Describe the question or bug
模块执行arkctl deploy出现报错，找不到ApolloPropertiesClearInitializer

### Expected behavior
期望能正常装载

### Actual behavior

```
com.alipay.sofa.koupleless.arklet.core.common.exception.ArkletRuntimeException: java.lang.reflect.InvocationTargetException
	at com.alipay.sofa.koupleless.arklet.core.command.builtin.handler.InstallBizHandler.handle(InstallBizHandler.java:78)
	at com.alipay.sofa.koupleless.arklet.core.command.builtin.handler.InstallBizHandler.handle(InstallBizHandler.java:57)
	at com.alipay.sofa.koupleless.arklet.core.command.CommandServiceImpl.process(CommandServiceImpl.java:178)
	at com.alipay.sofa.koupleless.arklet.core.api.tunnel.http.netty.NettyHttpServer$NettyHttpHandler.channelRead0(NettyHttpServer.java:170)
	at com.alipay.sofa.koupleless.arklet.core.api.tunnel.http.netty.NettyHttpServer$NettyHttpHandler.channelRead0(NettyHttpServer.java:149)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerExpectContinueHandler.channelRead(HttpServerExpectContinueHandler.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:55)
	at com.alipay.sofa.ark.container.model.BizModel.doStart(BizModel.java:339)
	at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:321)
	at com.alipay.sofa.ark.api.ArkClient.doInstallBiz(ArkClient.java:195)
	at com.alipay.sofa.ark.api.ArkClient.installBiz(ArkClient.java:169)
	at com.alipay.sofa.ark.api.ArkClient.doInstallOperation(ArkClient.java:388)
	at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:370)
	at com.alipay.sofa.koupleless.arklet.core.ops.strategy.InstallOnlyStrategy.install(InstallOnlyStrategy.java:52)
	at com.alipay.sofa.koupleless.arklet.core.ops.UnifiedOperationServiceImpl.install(UnifiedOperationServiceImpl.java:71)
	at com.alipay.sofa.koupleless.arklet.core.command.builtin.handler.InstallBizHandler.handle(InstallBizHandler.java:69)
	... 35 common frames omitted
Caused by: java.lang.IllegalArgumentException: Unable to instantiate com.alipay.sofa.koupleless.adapter.ApolloPropertiesClearInitializer [org.springframework.boot.env.EnvironmentPostProcessor]
	at org.springframework.boot.util.Instantiator.lambda$static$0(Instantiator.java:53)
	at org.springframework.boot.util.Instantiator.instantiate(Instantiator.java:153)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.springframework.boot.util.Instantiator.instantiate(Instantiator.java:141)
	at org.springframework.boot.util.Instantiator.instantiate(Instantiator.java:126)
	at org.springframework.boot.env.ReflectionEnvironmentPostProcessorsFactory.getEnvironmentPostProcessors(ReflectionEnvironmentPostProcessorsFactory.java:72)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.getEnvironmentPostProcessors(EnvironmentPostProcessorApplicationListener.java:122)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:100)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:87)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:301)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at com.corpgovernment.fulfillment.Biz1Application.main(Biz1Application.java:29)
	... 49 common frames omitted
Caused by: com.alipay.sofa.ark.exception.ArkLoaderException: [ArkBiz Loader] order-fulfillment-flight:1.0-SNAPSHOT : can not load class: com.alipay.sofa.koupleless.adapter.ApolloPropertiesClearInitializer
```

### Environment

- Koupleless version (see CURRENT_VERSION.txt):1.3.2
- SOFAArk version:2.2.15
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):Darwin Kernel Version 21.5.0
- Kubernetes version: /

**Comment by lvjing2** [comment]
![image](https://github.com/user-attachments/assets/1283ca0f-3476-4ddf-9122-fc4ca75ac25f)

模块里有没有执行 resource Loader，可以参考这个指定下
https://github.com/koupleless/samples/blob/main/springboot-samples/web/tomcat/biz1-web-single-host/src/main/java/com/alipay/sofa/web/biz1/Biz1Application.java

**Comment by Marco-Zheng** [comment]
> ![image](https://private-user-images.githubusercontent.com/3754074/393674179-1283ca0f-3476-4ddf-9122-fc4ca75ac25f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MTM2OTgsIm5iZiI6MTczMzcxMzM5OCwicGF0aCI6Ii8zNzU0MDc0LzM5MzY3NDE3OS0xMjgzY2EwZi0zNDc2LTRkZGYtOTEyMi1mYzRjYTc1YWMyNWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMDMwMzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzc2OWFkMTRlZGQ5MjQxOWNjNDJkODE0ZTk2ODQ2ZTQzMzhiNGUyM2Q2NWFmYTkyNDhkZGQ5MjQzMjEzZjIxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.doGIpcxW9Mjb6_vKdGBCkYBV_t1p6sJ5TattcBevjGc)
> 
> 模块里有没有执行 resource Loader，可以参考这个指定下 https://github.com/koupleless/samples/blob/main/springboot-samples/web/tomcat/biz1-web-single-host/src/main/java/com/alipay/sofa/web/biz1/Biz1Application.java


看起来使用这种方式后，不需要在模块里面引用这个包了（之前引用这个包貌似也可以解决这个问题），但是有几个点比较疑惑
    <dependency>
      <groupId>com.alipay.sofa.koupleless</groupId>
      <artifactId>koupleless-adapter-apollo-1.6</artifactId>
      <version>1.2.2</version>
    </dependency>

1、基座里面需要根据使用的中间件自己手动引入对应的adapter吗？我记得文档中提到编译时貌似会自动下载？
2、为啥要在代码中手动执行下面的操作
```
ResourceLoader resourceLoader = new DefaultResourceLoader(
                Biz1Application.class.getClassLoader());
        builder.resourceLoader(resourceLoader);
        builder.build().run(args);
```
3、目前在模块中添加了以上代码，但是出现以下问题
<img width="1134" alt="image" src="https://github.com/user-attachments/assets/c711e437-d474-4196-94e9-6460a1160771">
debug发现 DruidDatabaseProperties 里的数据都是null，猜测是Apollo的数据没有获取到
![image](https://github.com/user-attachments/assets/50046fa1-dab8-4d29-9e95-55385f4d061b)

DruidDatabaseProperties的代码如下
```
@Data
@ToString
@ConfigurationProperties(prefix = DruidDatabaseProperties.DRUID_PREFIX)
public class DruidDatabaseProperties {

    static final String DRUID_PREFIX = "spring.druid";

    private String druidClassName;
    private String url;
    private String username;
    private String password;
....
```

**Comment by lvjing2** [comment]
1. 嗯，不需要手动指定了，那部分文档没更新过来。基座里有个plugin会自动引入的
2.

**Comment by Marco-Zheng** [comment]
> 1. 嗯，不需要手动指定了，那部分文档没更新过来。基座里有个plugin会自动引入的
> 2. 参考 Apollo 的samples的吗？ samples里没看到这个问题

不是的，目前是用我们生产真实的服务进行改造出现这个问题，看起来是基座中Spring中的Properties没有注入进来，有啥排查思路吗？

另外上面提到的第二个问题还是没有理解，麻烦解答下，谢谢。 @lvjing2

**Comment by gaosaroma** [comment]
> 看起来是基座中Spring中的Properties没有注入进来

是指基座中的什么 properties 在模块中没有生效？基座的 application.properties 和 模块的 application.properties 本身就是隔离的。

**Comment by Marco-Zheng** [comment]
> > 看起来是基座中Spring中的Properties没有注入进来
> 
> 是指基座中的什么 properties 在模块中没有生效？基座的 application.properties 和 模块的 application.properties 本身就是隔离的。

@gaosaroma 请问
1、如果模块想和基座复用Environment（共用Properties）该怎么处理呢？
2、如果模块和基座本身就是隔离的，目前我在模块中也添加了apollo配置（和基座相同），可是依然获取不到配置
<img width="559" alt="image" src="https://github.com/user-attachments/assets/61ba8851-f97f-429d-8a09-9418e68166a9">

**Comment by gaosaroma** [comment]
> 1、如果模块想和基座复用Environment（共用Properties）该怎么处理呢？
在基座中配置 ark.common.env.share.keys，指定模块可以共享的 properties

2、如果模块和基座本身就是隔离的，目前我在模块中也添加了apollo配置（和基座相同），可是依然获取不到配置
首先，可以在 com.alipay.sofa.koupleless.plugin.spring.ServerlessEnvironmentPostProcessor#postProcessEnvironment 处 debug 看看是否模块生效了配置；其次可以在获取配置的地方，看看模块的 enviroment 和预期是否相符。

**Comment by Marco-Zheng** [comment]
> > 1、如果模块想和基座复用Environment（共用Properties）该怎么处理呢？
> 
> 在基座中配置 ark.common.env.share.keys，指定模块可以共享的 properties
> 
> > 2、如果模块和基座本身就是隔离的，目前我在模块中也添加了apollo配置（和基座相同），可是依然获取不到配置
> 
> 首先，可以在 com.alipay.sofa.koupleless.plugin.spring.ServerlessEnvironmentPostProcessor#postProcessEnvironment 处 debug 看看是否模块生效了配置；其次可以在获取配置的地方，看看模块的 enviroment 和预期是否相符。

目前debug发现获取不到配置是因为，模块启动过程中在initMetaServerProviders报错
<img width="1597" alt="image" src="https://github.com/user-attachments/assets/877166cc-9887-4351-889c-31ac2f2d8f73">
原因是Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: com.ctrip.framework.apollo.core.spi.MetaServerProvider: Provider com.ctrip.corp.obt.generic.apollo.internals.TenantMetaServerProvider not a subtype

TenantMetaServerProvider是我们重写MetaServerProvider的类，TenantMetaServerProvider implements MetaServerProvider
<img width="877" alt="image" src="https://github.com/user-attachments/assets/5682194e-ba88-48b0-ad0f-d104e48ab011">

看起来是java ServiceLoader<S> loader = ServiceLoader.load(clazz); 发现TenantMetaServerProvider不是MetaServerProvider的子类，但是基座启动是没有这个问题的 @lvjing2 @gaosaroma 
<img width="1124" alt="image" src="https://github.com/user-attachments/assets/03423b28-c2de-43fd-aaaf-b8c3cd33f564">

**Comment by lvjing2** [comment]
方便的话，可以群里聊哈
