### ISSUE TITLE
Hessian serializer problem leading to Java heap space

### ISSUE THREAD

**Issue by linwaiwai** [koupleless/koupleless#81]
### Describe the question or bug

```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3746) ~[?:?]
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:120) ~[?:?]
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:95) ~[?:?]
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:156) ~[?:?]
	at com.caucho.hessian.io.Hessian2Output.flushBuffer(Hessian2Output.java:1628) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.Hessian2Output.writeByteStream(Hessian2Output.java:1283) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.InputStreamSerializer.writeObject(InputStreamSerializer.java:70) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:465) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.UnsafeSerializer$ObjectFieldSerializer.serialize(UnsafeSerializer.java:299) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.UnsafeSerializer.writeInstance(UnsafeSerializer.java:218) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.UnsafeSerializer.writeObject(UnsafeSerializer.java:172) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:465) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.UnsafeSerializer$ObjectFieldSerializer.serialize(UnsafeSerializer.java:299) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.UnsafeSerializer.writeInstance(UnsafeSerializer.java:218) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.UnsafeSerializer.writeObject(UnsafeSerializer.java:172) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:465) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.UnsafeSerializer$ObjectFieldSerializer.serialize(UnsafeSerializer.java:299) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.UnsafeSerializer.writeInstance(UnsafeSerializer.java:218) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.UnsafeSerializer.writeObject(UnsafeSerializer.java:172) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:465) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.UnsafeSerializer$ObjectFieldSerializer.serialize(UnsafeSerializer.java:299) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.UnsafeSerializer.writeInstance(UnsafeSerializer.java:218) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.UnsafeSerializer.writeObject(UnsafeSerializer.java:172) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:465) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.UnsafeSerializer$ObjectFieldSerializer.serialize(UnsafeSerializer.java:299) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.UnsafeSerializer.writeInstance(UnsafeSerializer.java:218) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.UnsafeSerializer.writeObject(UnsafeSerializer.java:172) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:465) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.UnsafeSerializer$ObjectFieldSerializer.serialize(UnsafeSerializer.java:299) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.UnsafeSerializer.writeInstance(UnsafeSerializer.java:218) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.UnsafeSerializer.writeObject(UnsafeSerializer.java:172) ~[hessian-4.0.66.jar:3.1.0]
	at com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:465) ~[hessian-4.0.66.jar:3.1.0]
```

### Expected behavior

I have a biz function 
```
public Mono<Void> filter(ServerWebExchange exchange, Map<String, Object> config) ;
```
when master biz invoking the biz function ， the problem happens.
 
Mono, ServerWebExchange, Map in the biz are provided by master biz.

### Actual behavior

when I trace the bug, I got:

```
// SpringServiceInvoker.java
private Object invokeServiceCrossClassLoader(MethodInvocation invocation)
                                                                             throws InvocationTargetException,
                                                                             IllegalAccessException){
....
   Object[] serviceMethodArguments = (Object[]) serializeTransform(clientMethodArguments,
            serviceClassLoader);
   Class[] serviceMethodArgumentTypes = (Class[]) serializeTransform(
            clientMethodArgumentTypes, serviceClassLoader);
....
}

```

```
// serializeTransform.java

     public static Object serializeTransform(Object source, ClassLoader targetClassLoader) {
        Object target;
        ClassLoader currentContextClassloader = Thread.currentThread().getContextClassLoader();
        try {
            if (targetClassLoader != null) {
                Thread.currentThread().setContextClassLoader(targetClassLoader);
            }
            SerializerFactory serializerFactory = new SerializerFactory();
            serializerFactory.setAllowNonSerializable(true);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            Hessian2Output h2o = new Hessian2Output(bos);
            h2o.setSerializerFactory(serializerFactory);
            h2o.writeObject(source);
            h2o.flush();
            byte[] content = bos.toByteArray();

            Hessian2Input h2i = new Hessian2Input(new ByteArrayInputStream(content));
            h2i.setSerializerFactory(serializerFactory);
            target = h2i.readObject();
        } catch (IOException ex) {
            throw new RuntimeException(ex);
        } finally {
            Thread.currentThread().setContextClassLoader(currentContextClassloader);
        }
        return target;
    }
```

Since the source can been array， the lacking of judge source to single or array could be the issue to make "JAVA HEAP" happen.

### Environment

- Koupleless version (see CURRENT_VERSION.txt):0.5.6
- SOFAArk version:3.1.3 (v3.1.3)
- JVM version (e.g. `java -version`): 18
- OS version (e.g. `uname -a`): Darwin MacBook-Pro.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020 x86_64
- Kubernetes version: none

**Comment by lvjing2** [comment]
fixed by #87
